Nav-Bar updated.
madina0801/JobTrackr pull request #6
Opened 2024-02-03 22:36 UTC by sanketyelave

2024-02-04 14:27 UTC, madina0801 requested changes

2024-02-04 14:27 UTC, madina0801 commented on src/components/layout/Navbar.jsx
> +                    <li><a className="main-nav-link" href="https://github.com/madina0801/JobTrackr" >GitHub</a></li>
Sorry, forgot to mention the GitHub page should be opened in new browser tab (target=”_blank")

2024-02-04 14:27 UTC, madina0801 commented on src/components/layout/Navbar.jsx
> +            <div className="heading-primary" style={{ position: 'absolute', left: '50%', transform: 'translateX(-50%)' }}>JobTracker</div>
The title is "JobTrackr"

2024-02-05 13:09 UTC, sanketyelave commented
Changes are done , let me know if  any more modification required.

2024-02-05 16:29 UTC, merged